services:
  - type: web
    name: api-traqueamento
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: traqueamento
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FB_API_URL
        value: https://graph.facebook.com/v18.0
      - key: FB_PIXEL_ID
        sync: false
      - key: FB_ACCESS_TOKEN
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: MAXMIND_ACCOUNT_ID
        sync: false
      - key: MAXMIND_LICENSE_KEY
        sync: false
    healthCheckPath: /v1/status
    autoDeploy: true
    plan: free 